default: &default
  adapter: postgresql
  database: docker_example_rails
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host:     <%= ENV['DATABASE_HOST'] %>
  port:     <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: docker_example_rails_development

test:
  <<: *default
  database: docker_example_rails_test

production:
  <<: *default
  database: docker_example_rails_production
